services:
  - type: web
    name: kaamsetu-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_TRANSLATE_API_KEY
        sync: false
      - key: GOOGLE_TTS_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
