'use client';

import { useState } from 'react';

export default function PolicyBrief({ briefData, onGenerate, isLoading }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard?.writeText(briefData?.brief_text || '');
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportPDF = async () => {
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();

      doc.setFontSize(18);
      doc.setTextColor(26, 58, 107);
      doc.text('KaamSetu — Policy Intelligence Brief', 20, 20);

      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(`Generated: ${new Date(briefData.generated_at).toLocaleString()}`, 20, 28);
      doc.text(`Data Points: ${briefData.data_points} workers | ${briefData.distress_signals} distress signals`, 20, 34);

      doc.setDrawColor(255, 153, 51);
      doc.setLineWidth(0.5);
      doc.line(20, 38, 190, 38);

      // Brief text
      doc.setFontSize(11);
      doc.setTextColor(30);
      const lines = doc.splitTextToSize(briefData.brief_text, 170);
      doc.text(lines, 20, 46);

      // Urgency badge
      const urgencyY = 46 + lines.length * 5 + 10;
      doc.setFontSize(12);
      doc.setTextColor(220, 38, 38);
      doc.text(`URGENCY: ${briefData.urgency}`, 20, urgencyY);

      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(`Responsible: ${briefData.recommended_ministry}`, 20, urgencyY + 8);

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text('Generated by KaamSetu AI — BRICS Worker Safety Net', 20, 285);
      doc.text('CONFIDENTIAL — For authorized ministry use only', 120, 285);

      doc.save(`KaamSetu-PolicyBrief-${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (err) {
      console.error('PDF export failed:', err);
    }
  };

  return (
    <div className="space-y-4">
      {/* Generate button */}
      {!briefData && (
        <button
          onClick={onGenerate}
          disabled={isLoading}
          className="w-full py-3 bg-[#1a3a6b] text-white rounded-xl font-semibold text-sm
                     hover:bg-[#15305a] transition-colors disabled:opacity-50 flex items-center justify-center gap-2"
        >
          {isLoading ? (
            <>
              <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
              Generating AI Brief...
            </>
          ) : (
            <>
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Generate Policy Brief
            </>
          )}
        </button>
      )}

      {/* Brief display */}
      {briefData && (
        <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
          {/* Header */}
          <div className="bg-slate-50 border-b border-slate-200 px-4 py-3 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className={`w-2 h-2 rounded-full ${
                briefData.urgency === 'CRITICAL' ? 'bg-red-500 animate-pulse' :
                briefData.urgency === 'HIGH' ? 'bg-red-500' :
                briefData.urgency === 'MEDIUM' ? 'bg-orange-500' : 'bg-green-500'
              }`} />
              <span className="text-xs font-semibold text-slate-600 uppercase tracking-wider">
                AI Policy Brief — {briefData.urgency}
              </span>
            </div>
            <span className="text-[10px] text-slate-400">
              {new Date(briefData.generated_at).toLocaleString()}
            </span>
          </div>

          {/* Content */}
          <div className="p-4">
            <pre className="whitespace-pre-wrap text-sm text-slate-700 font-sans leading-relaxed">
              {briefData.brief_text}
            </pre>
          </div>

          {/* Actions */}
          <div className="border-t border-slate-200 px-4 py-3 flex gap-2">
            <button
              onClick={handleExportPDF}
              className="flex-1 py-2 bg-[#1a3a6b] text-white text-xs font-semibold rounded-lg
                         hover:bg-[#15305a] transition-colors flex items-center justify-center gap-1"
            >
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Export PDF
            </button>
            <button
              onClick={handleCopy}
              className="flex-1 py-2 border border-slate-200 text-slate-600 text-xs font-semibold rounded-lg
                         hover:bg-slate-50 transition-colors flex items-center justify-center gap-1"
            >
              {copied ? '✓ Copied!' : '📋 Copy'}
            </button>
            <button
              onClick={onGenerate}
              disabled={isLoading}
              className="py-2 px-3 border border-slate-200 text-slate-600 text-xs rounded-lg
                         hover:bg-slate-50 transition-colors disabled:opacity-50"
            >
              🔄
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
